### ISSUE TITLE
生效

### ISSUE THREAD

**Issue by moQingTing** [SSBun/FlyCoding#1]
在Xcode 如何才能生效？

**Comment by SSBun** [comment]
![image](https://user-images.githubusercontent.com/13583118/69125082-f0abd800-0adf-11ea-95a8-e1ab17e81d34.png)
然后在 Xcode 的菜单栏 -> Editor 最下面应该能看到 FlyCoding， 最好在 Xcode 中设置一个快捷键， 我是用的 cmd+P
![image](https://user-images.githubusercontent.com/13583118/69125206-42546280-0ae0-11ea-9416-386c27d4a74c.png)
